version: '3'

networks:
  inception:
    driver: bridge

volumes:
  wordpress:
    driver_opts:
      type: none
      o: bind
      device: /home/gbohm/data/wordpress

  mariadb:
    driver_opts:
      type: none
      o: bind
      device: /home/gbohm/data/mariadb

services:
  nginx:
    container_name: nginx
    image: nginx
    build:
      context: ./requirements/nginx
    restart: always
    volumes:
      - wordpress:/var/www/html
    ports:
      - 443:443
    depends_on:
      - wordpress
    networks:
      - inception
    env_file:
      - .env

  mariadb:
    container_name: mariadb
    image: mariadb
    build:
      context: ./requirements/mariadb
    restart: always
    volumes:
      - mariadb:/var/lib/mysql
    expose:
      - 3306
    networks:
      - inception
    env_file:
      - .env

  wordpress:
    container_name: wordpress
    image: wordpress
    build:
      context: ./requirements/wordpress
    restart: always
    volumes:
      - wordpress:/var/www/html
    expose:
      - 9000
    depends_on:
      - mariadb
    networks:
      - inception
    env_file:
      - .env