version: '3'

networks:
  inception:

volumes:
  wordpress:
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wordpress

  mariadb:
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/mariadb

services:
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception
    env_file:
      - .env

  wordpress:
    container_name: wordpress
    image: wordpress
    restart: always
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception
    env_file:
      - .env

  mariadb:
    container_name: mariadb
    image: mariadb
    restart: always
    volumes:
      - mariadb:/var/lib/mariadb
    networks:
      - inception
    env_file:
      - .env